dependencies:
- anaconda-client=1.2.2=py34_0
- appnope=0.1.0=py34_0
- backports_abc=0.4=py34_0
- basemap=1.0.7=np110py34_0
- bcolz=0.12.1=np110py34_0
- bitarray=0.8.1=py34_0
- blosc=1.2.7=py34_0
- bloscpack=0.8.0=nppy34_0
- bokeh=0.11.1=py34_0
- castra=0.1.3=nppy34_0
- chest=0.2.3=py34_0
- cloudpickle=0.1.1=py34_0
- clyent=1.2.1=py34_0
- cycler=0.9.0=py34_0
- dask=0.8.0=py34_0
- decorator=4.0.9=py34_0
- docopt=0.6.2=py34_0
- freetype=2.5.5=0
- funcsigs=0.4=py34_0
- geos=3.3.3=0
- hdfs=2.0.4=py34_0
- heapdict=1.0.0=py34_0
- ibis-framework=0.6.0=py34_0
- impyla=0.12.0=py34_0
- ipykernel=4.2.2=py34_0
- ipython=4.1.1=py34_0
- ipython_genutils=0.1.0=py34_0
- ipywidgets=4.1.1=py34_0
- jbig=2.1=0
- jinja2=2.8=py34_0
- jpeg=8d=1
- jsonschema=2.4.0=py34_0
- jupyter=1.0.0=py34_1
- jupyter_client=4.1.1=py34_0
- jupyter_console=4.1.0=py34_0
- jupyter_core=4.0.6=py34_0
- libgd=2.1.1=0
- libpng=1.6.17=0
- libtiff=4.0.6=1
- libwebp=0.5.0=0
- locket=0.2.0=py34_0
- markupsafe=0.23=py34_0
- matplotlib=1.5.1=np110py34_0
- mistune=0.7.1=py34_0
- mkl=11.3.1=0
- mock=1.3.0=py34_0
- nbconvert=4.1.0=py34_0
- nbformat=4.0.1=py34_0
- notebook=4.1.0=py34_0
- numpy=1.10.4=py34_0
- openssl=1.0.2f=0
- pandas=0.17.1=np110py34_0
- partd=0.3.2=py34_1
- path.py=8.1.2=py34_1
- pbr=1.3.0=py34_0
- pexpect=3.3=py34_0
- pickleshare=0.5=py34_0
- pip=8.0.3=py34_0
- ply=3.8=py34_0
- psutil=3.4.2=py34_0
- ptyprocess=0.5=py34_0
- py=1.4.31=py34_0
- pygments=2.1.1=py34_0
- pyparsing=2.0.3=py34_0
- pyqt=4.11.4=py34_1
- pytest=2.8.5=py34_0
- python=3.4.4=0
- python-dateutil=2.4.2=py34_0
- python.app=1.2=py34_4
- pytz=2015.7=py34_0
- pyyaml=3.11=py34_1
- pyzmq=15.2.0=py34_0
- qt=4.8.7=1
- qtconsole=4.1.1=py34_0
- readline=6.2=2
- requests=2.9.1=py34_0
- setuptools=20.1.1=py34_0
- simplegeneric=0.8.1=py34_0
- sip=4.16.9=py34_0
- six=1.10.0=py34_0
- sqlalchemy=1.0.12=py34_0
- sqlite=3.9.2=0
- terminado=0.5=py34_1
- thrift=0.9.3=py34_0
- thrift_sasl=0.1.0=py34_0
- thriftpy=0.3.2=py34_0
- tk=8.5.18=0
- toolz=0.7.4=py34_0
- tornado=4.3=py34_0
- traitlets=4.1.0=py34_0
- ujson=1.35=py34_0
- wheel=0.29.0=py34_0
- xarray=0.7.1=py34_0
- xz=5.0.5=1
- yaml=0.1.6=0
- zlib=1.2.8=0
- pip:
  - arpeggio==1.2.1
  - backports-abc==0.4
  - cython==0.23.4
  - future==0.15.2
  - graphviz==0.4.10
  - h5py==2.5.0
  - ipython-genutils==0.1.0
  - jagged==0.1.0
  - joblib==0.9.4
  - jupyter-client==4.1.1
  - jupyter-console==4.1.0
  - jupyter-core==4.0.6
  - patsy==0.4.1
  - pymc3==3.0
  - scipy==0.17.0
  - theano==0.8.0.dev0
  - thrift-sasl==0.1.0
  - whatami==5.1.0

